### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [bonjin-app/Portfolio#1]
Hi,<br><br>url : https://github.com/bonjin-app/Portfolio/blob/820c03ce98b38d5340f726a7b0e2a07ed8623cc6/src/main/resources/application-dev.yml <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by bonjin-app** [comment]
Hi shaybenb

Thanks for reporting the problem.

It was a personal project, so I didn't care.

'WARNING' appeared in the exposed beta database table, but I didn't pay attention.

We will strengthen security and protect data.
